### PR TITLE
[WIP] Authentication with Clearance gem

### PR DESCRIPTION
**Pull request by ariaru**
NOT READY TO MERGE!!!

To do:

- Add tests for password edit and reset

### CODE REVIEW

**Comment by lisbethmarianne** [comment]
Something went wrong here. Why are there 41 commits? Trying to understand this.

**Comment by ariaru** [comment]
I'd guess that's because we rebased the branch onto master yesterday(?)

**Comment by fidothe** [comment]
looks more like a merge than a rebase. Def. weird

**Comment by fidothe** [comment]
fixed by @ariaru performing cherry-pick surgery on a new branch off master 😄 🕵🚑

**Pull request merged**
