### PR TITLE
markdown button css fix, close #212

### LINKED ISSUE #212: CSS of Markdown Preview in Form needs to be adjusted
@lislis We need your help! 

I didn't test my CSS for the markdown preview in different browsers. Also I have no idea how to fix this.

Chrome (looks fine):
bildschirmfoto 2016-06-12 um 14 23 25

Firefox (urrg): 
bildschirmfoto 2016-06-12 um 14 20 25

Feel free to rewrite the whole thing if you need to. 😛

### PR DESCRIPTION
**Pull request by bioshrimp**
fixed the tab buttons and the hint message for mobile

diversitytickets 2016-07-25 20-10-29

### CODE REVIEW

**Comment by lislis** [comment]
@lisbethmarianne do you have time to review this?

**Comment by lisbethmarianne** [comment]
Looks good in Firefox.

I have the line unter "write" or "preview" in Chrome:
bildschirmfoto 2016-08-08 um 19 42 33

And Safari is really weird:
bildschirmfoto 2016-08-08 um 19 45 43

**Comment by lislis** [comment]
@lisbethmarianne good catch 👀 . I think it's fixed ™️  now

**Comment by lisbethmarianne** [comment]
Looks good. Merging it. :shipit:

**Pull request merged**
