### PR TITLE
Basic image upload

### PR DESCRIPTION
**Pull request by lisbethmarianne**
Issue #46

We followed this tutorial: https://devcenter.heroku.com/articles/direct-to-s3-image-uploads-in-rails

```
S3_BUCKET=bucket_name AWS_ACCESS_KEY_ID=my_id AWS_SECRET_ACCESS_KEY=my_key rails s
```
If you want to test this locally you have to replace this with your own variables.

Update: Solves Issue #103

### CODE REVIEW

**Comment by lisbethmarianne** [comment]
- [ ] get ENVs on Heroku working
- [ ] make different buckets for production/staging/development
- [ ] get upload bar working
- [ ] go back (to 'new') from preview keeps the picture
- [ ] show picture when it is uploaded
- [ ] control picture sizes, thumbnails

**Comment by lisbethmarianne** [comment]
I have to uncheck the 'get upload bar working'. What I observe: I go to submit event (javascript files are not loaded), I upload an image - nothing happens, no loading bar. If I refresh the page, it is loading all the javascript (I can see it in the network tab), and everything works fine, loading bar is there.

**Comment by lisbethmarianne** [comment]
'get upload bar working': I removed turbolinks and everything works. This is probably not the solution. But maybe a good hint.

**Comment by lisbethmarianne** [comment]
3 buckets Sven made for us:
diversity-tickets-assets
diversity-tickets-assets-staging
diversity-tickets-assets-development

**Comment by lisbethmarianne** [comment]
I played around with showing the picture in the form after it is uploaded, I have one problem, I don't know how to approach, it would be cool to have the image showing between the label 'Logo' and the upload button. Any Idea? (Styling should be improved too.)

Before upload:
bildschirmfoto 2016-02-17 um 13 28 06

After upload:
bildschirmfoto 2016-02-17 um 13 28 26

**Comment by lisbethmarianne** [comment]
@lislis @bioshrimp and team: We hand this over to you! If you want to run this you have to add a .env file to the root with all the ENVs, I can send them to you or you can copy them from Heroku. 

You can show the logo wherever you like, we didn't really know where to include them. There is one in _event.html.erb (needs some resizing). And the upload form needs to be looked over. (We hate the green/red upload bar.)

If you need anything let me know.

**Comment by lislis** [comment]
Hey there! We added some styles for the upload progress bar. That is good to go now.
But  I would suggest that you rebase this PR first and we then decide where to display the logos. I'd rather not change too much in outdated templates. wdyt?

**Comment by lislis** [comment]
screen shot 2016-05-02 at 21 07 08
btw, this is how it looks like

**Pull request merged**
