### PR TITLE
Bump rails

### PR DESCRIPTION
**Pull request by lislis**
Minor version bump for rails

### CODE REVIEW

**Comment by lislis** [comment]
@mauditecandela @guainumbi @alicetragedy hey there! Not sure who is currently in charge of maintaining the app but I'd would be lovely to get some sort of feedback or comment or something :)
Otherwise I'll just go on and merge it myself :p

**Comment by alicetragedy** [comment]
hiya @lislis 👋 I'm currently on holiday so haven't had much time to look through notifications or emails let alone review PRs :) But this looks good to me so I think we can merge it 👍  thank you! ❤️

**Comment by lislis** [comment]
@alicetragedy oh no, didn't mean to disturb your holiday :see_no_evil: I'll just go ahead then

**Comment by anikalindtner** [comment]
thank you @lislis for this! <3

**Pull request merged**
