### PR TITLE
fix(app):replace Unapprove with Disapprove

### LINKED ISSUE #86: Remove all "Unapprove" to "Disapprove"
Since unapprove is not an English word.

### PR DESCRIPTION
**Pull request by ferbsx**
fixes #86

### CODE REVIEW

**Comment by joecorcoran** [comment]
We talked about this briefly last night. I think there's still an issue, in that the word "[disapproved](http://www.dict.cc/?s=disapproved)" means that something has been *actively* chosen as unacceptable. In our case, everything in the `approved = false` category is just *passively* categorised as such, by default.

Both "unapproved" (not strictly a real word, but useful) and "disapproved" don't really work. I would change the wording in the UI to "Approved events / Non-approved events" or you don't like that, simply "Approved events / Other events". In the code (scopes etc.) it doesn't matter that much, as long as we all know what we're talking about.

But let's not worry about this too much :)

> "The map is not the territory" &#8212; Alfred Korzybski

**Comment by fidothe** [comment]
oh man, I just commented on the issue. Sorry for the pile-on, @ferbsx.

**Comment by joecorcoran** [comment]
Grammar party! :tada:

**Comment by ferbsx** [comment]
I know! Unapproved is grammatically wrong but disapproved isn't the right word either! So taking your suggestions into account, I think "Approved events / Non-approved events" is the best option.

**Comment by fidothe** [comment]
Unapproved is a real word whose meaning is exactly what we want here (it's in the OED on your mac, thrill seekers). Unapprove would be a problem if you used it like disapprove, i.e. 'I unapprove of your new car', but using it in relation to "not officially accepted or sanctioned" is fine, i.e. 'I'm sorry but your permit shouldn't have been approved, so I'm going to have to unapprove it'.

**Comment by ferbsx** [comment]
Sorry, Unapprove^* is what I meant.

**Comment by ferbsx** [comment]
What do you suggest we do @fidothe ?

**Comment by fidothe** [comment]
If you're super keen to avoid 'Unapprove' I suggest the action becomes 'Reject'. And then I think we should all have a nice cup of tea and a piece of cake. Mmmmm, cake.

**Comment by lisbethmarianne** [comment]
"Reject" sounds really wrong to me. Because also newly submitted events are "unapproved".

**Comment by fidothe** [comment]
Wah, no cake for me...

New events are indeed submitted unapproved, which means the only action available is to approve them. You could only reject events that had been approved... I think the list of unapproved events should be call 'unapproved' and definitely not 'rejected'

**Comment by ariaru** [comment]
Joe suggested "non-approved" for the user interface. I'd vote for that :+1: 
Everything else could stay as it is now, yay!
:smile:

**Comment by ariaru** [comment]
:cake: for Matt!

**Comment by ariaru** [comment]
Ah, yes, the action. We could also talk about this again (briefly) next week and decide then, it shouldn't be too hard by now?

**Comment by thatbettina** [comment]
What about 'waiting for human approval'?

**Comment by Powerglove** [comment]
See issue #86

**Pull request closed without merging**
