### PR TITLE
two column layout

### PR DESCRIPTION
**Pull request by lislis**
Also fixes wrong edit path in admin_events#index

### CODE REVIEW

**Comment by lislis** [comment]
All cool, @ariaru maybe you wanna merge right away?

**Comment by lislis** [comment]
Rebased and good to go!

**Comment by lislis** [comment]
@lisbethmarianne do you want to check again? We unfortunately can't make it as 'fluent' as it is in the design comps right now

**Comment by lisbethmarianne** [comment]
Is there a way to remove the space between Application Details and Selection Process?

**Comment by lisbethmarianne** [comment]
I rebased that and removed the 2 column layout from the form partial. Can somebody take a look if there got something lost in the rebase? If it's fine we should merge this.

@lislis We can add the 2 column layout back, but I thought it didn't look right on the submit event page. 😕

**Comment by lisbethmarianne** [comment]
@lislis We were checking this again and it doesn't look so nice if you have long event names. In both events and admin index.

bildschirmfoto 2016-07-11 um 19 18 06

bildschirmfoto 2016-07-11 um 19 14 34


The 2 column layout is missing from past events.

**Comment by lislis** [comment]
Closing this in favor of https://github.com/rubymonsters/diversity_ticketing/pull/232

**Pull request closed without merging**
