### PR TITLE
approve & unapproved icons

### PR DESCRIPTION
**Pull request by bioshrimp**
Admin area: adding the **"approve" & "unapproved" icons** for events. 

diversitytickets 2016-09-24 13-00-32

### CODE REVIEW

**Comment by lisbethmarianne** [comment]
This looks really good. I have one little thing: the unapprove tooltip is missing the e:

tooltip

**Comment by bioshrimp** [comment]
true. 
@lislis in this case I could increase the fixed tooltip width to 6em to make the "unapprove" fit but it would probably better just to have a flexible width that adjust to text length? Unfortunately I am not able to figure out how. I am so lame. Tried with min-width and max-width but not working. maybe you have a suggestion? :)

**Comment by bioshrimp** [comment]
@lisbethmarianne I set an extra class for the approved/approved tooltip because we have to stick to fixed width in this case. So tooltip length for approved/unapproved should not be cut off anymore. hope all is good to go. :)

tooltip-large

**Comment by lisbethmarianne** [comment]
:shipit:

**Pull request merged**
