### PR TITLE
Add images, close #202

### LINKED ISSUE #202: Add logos to events
Once #102 is merged, we can start putting the logos everywhere. In all the lists and other places.

### PR DESCRIPTION
**Pull request by lislis**
adding images and stuff

### CODE REVIEW

**Comment by lislis** [comment]
@saltinejustine could you render a 120x120 pixel placeholder image for conference logos? Maybe just the 'ticket' from the Diversity Tickets logo?

**Comment by saltinejustine** [comment]
Compressed because it's an svg which isn't supported yet in GH issues.

[DT-Placeholder.svg.zip](https://github.com/rubymonsters/diversity_ticketing/files/382358/DT-Placeholder.svg.zip)

**Comment by lislis** [comment]
Ah sorry, I should have been more specific. Could you make it a png?

**Comment by saltinejustine** [comment]
Sure

Sure.

dt-placeholder

**Comment by lislis** [comment]
@lisbethmarianne do you want to check if that's all working for you?

**Comment by lisbethmarianne** [comment]
Hi @lislis, this is super cool. ❤️  💛  💚 

One small thing:
I tested it with a round logo that had no background (?). Looked like this:

bildschirmfoto 2016-08-02 um 14 05 57

Would it be possible to remove `background-color: mix($grey-light, $grey-dark);`?

**Comment by lislis** [comment]
sure thing!

**Comment by lisbethmarianne** [comment]
Thanks. Merging this. :shipit:

**Comment by lisbethmarianne** [comment]
@lislis I pushed to heroku and the placeholder picture doesn't show. Can you have a look? https://diversitytickets.org/past_events

**Pull request merged**
