### PR TITLE
change from Mandrill to Postmark

### PR DESCRIPTION
**Pull request by Powerglove**

### CODE REVIEW

**Comment by lisbethmarianne** [comment]
@Powerglove Is this ready to merge? Thanks for taking care of this. 👍

**Comment by Powerglove** [comment]
Yes, please go ahead! :)

**Comment by lisbethmarianne** [comment]
I see you have the ENVs at staging but not in production.

**Comment by Powerglove** [comment]
true, we have to do the whole thing for prodution as well :/ i forgot

**Comment by svenfuchs** [comment]
super! 👍

**Pull request merged**
