### PR TITLE
Add contributing workflow

### PR DESCRIPTION
**Pull request by ferbsx**
Issue #90

### CODE REVIEW

**Comment by alicetragedy** [comment]
This is cool!! I would maybe add something about setting up the postgres database and running the tests to lower the barrier for people who want to contribute. What do you think? (that would be a small improvement on the already thorough readme)

**Comment by ferbsx** [comment]
Yea! For sure! I'm preparing a pretty in depth description of how to set everything up. I just have to figure it out for different operating systems. 
Sneak Peek: :wink: 
screen shot 2016-01-13 at 3 18 45 pm

**Comment by alicetragedy** [comment]
This is super awesome @ferbsx! As far as the current PR is concerned it looks good to go .. but that's maybe not my place to say :D

**Comment by lisbethmarianne** [comment]
Super cool, thanks @ferbsx !

**Comment by ariaru** [comment]
There are short descriptions on Postgres set-up by Joe, perhaps useful: https://gist.github.com/joecorcoran/02217948fa1e80d26b56
:)

**Pull request merged**
