### PR TITLE
Automatically tweet event after approval

### PR DESCRIPTION
**Pull request by ariaru**
addresses #200 
- [x] tests still missing
- [x] other tests currently failing because tokens are not adapted for test environment
- [x] use mocking to test Twitter integration to fix this ^
- [x] create Twitter application for Twitter account that should send out the tweets, add tokens as ENVs to Heroku before deploying
- [x] @anikalindtner Please review the tweet text :)

### CODE REVIEW

**Comment by anikalindtner** [comment]
@lisbethmarianne could you paste me the text in here? that would make it easier for me - then i don't need to look in the code base if i find it :D

**Comment by lisbethmarianne** [comment]
@ariaru What was the exact problem with this? Was it about the decision where the tweeting should happen?

**Comment by ariaru** [comment]
@anikalindtner: this is our placeholder tweet text: "#{event_name} is a new event on #{event_url} ! Check it out :)", just tell us what you want the tweets to say instead.
The other issue was: what Twitter account should be used (Travis Foundation's or a new one specifically for Diversity Tickets. I guess there are pros and cons for both, please decide :)

**Comment by anikalindtner** [comment]
@ariaru sorry, this dropped off my radar for whatever reason. /o\ You can always ping me in the slack channels as well when i don't react fast enough (or ever). 

"So great! #{event_name} is offering free diversity tickets! Apply until #{event_deadline} #{event_url} !" #OSS ##{event_location}"

would be awesome, if we could swap #{event_name} could become #{event_twitterhandle}, but we need to ask that in the form first before we can use it :D. So could you add that to the event form soon?

**Comment by lisbethmarianne** [comment]
We confirmed this is working for staging. We can not really test this for production, so if you approve an event @anikalindtner @alicetragedy next time, check the twitter account of travis foundation if a tweet was made.

We can always adjust the text to include the twitter handle, but we will do that in another PR.

**Comment by alicetragedy** [comment]
@lisbethmarianne I will remember that the next time we approve an event! thank you.

**Pull request merged**
