### PR TITLE
all the css things

### PR DESCRIPTION
**Pull request by lislis**

### CODE REVIEW

**Comment by lislis** [comment]
We have this in a mergable state now that has base styles for most of the elements, the topbar and the admin page. (But still far from done ;))
I think it makes sense to have that in master before Christmas so there is a base to start from in the new year and people can try things out if they want to

**Comment by joecorcoran** [comment]
Looks great so far! :rocket:

**Comment by lislis** [comment]
@joecorcoran just have to make Travis pass :D

**Comment by lislis** [comment]
Nice :dancer:

**Comment by lisbethmarianne** [comment]
I'm fine with merging. Looks great so far. Thanks a lot. :blush:

**Comment by ariaru** [comment]
:tada:
So I merged it. Thanks CSS group! :smile:

**Comment by lislis** [comment]
wheeee \o/

**Comment by ariaru** [comment]
@lislis Just one thing I noticed: in the events admin show view, the way the applications are displayed doesn't look like a table, but like this:
screenshot from 2015-12-17 01 21 00
Would be nice to have columns (or inline-block list items that pretend they are columns) for Name and Email instead, no? :)

**Comment by lisbethmarianne** [comment]
@ariaru When you go to the slack channel you will find some pictures how the final page will look like. This is just the beginning.

**Comment by lislis** [comment]
Yes! Also I didn't want to change too much markup before the winter break ;)

**Comment by ariaru** [comment]
I see :)

**Pull request merged**
