### PR TITLE
[WIP] Applicant selection process

### PR DESCRIPTION
**Pull request by ariaru**
This should take care of issue #199 , even though it currently doesn't make a difference regarding the T&C (as was provisionally decided in Slack discussion).

### CODE REVIEW

**Comment by svenfuchs** [comment]
Woha! Great work, @ariaru!

**Comment by ariaru** [comment]
@anikalindtner If you could review the wording soon-ish, that would be awesome, so we could be merge this :)

**Comment by anikalindtner** [comment]
hej @ariaru could you send me screenshots of the text where you need my 👀  on the wording? that would be way easier for me then, thank you <3

**Comment by ferbsx** [comment]
closes #199

**Pull request merged**
