### PR TITLE
Link events to organizers

### PR DESCRIPTION
**Pull request by ariaru**
Edit 1:
After rebase: Pop-up is broken, green flash message is back (have to figure out why). Do not merge yet...

Edit 2 (June 28th):
Pop-up working again (popup.js had to be explicitly required after rebase when require_tree wasn't used any more), yay!
But: some view( part)s are still missing that will enable users to actually edit their events. These should be added before merging this.

### CODE REVIEW

**Comment by ariaru** [comment]
@bioshrimp @lislis : There should probably be a more extensive (than just the flash message "Please sign in to continue") explanation for non-logged-in users that they have to have signed up and be logged in in order to submit an event. Can you take care of this please? :)

**Comment by ariaru** [comment]
Pop-up is broken -- do not merge!

**Comment by lislis** [comment]
@ariaru what's broken?

**Comment by ariaru** [comment]
@lislis The pop-up does not pop up, instead we get this (after clicking on "Submit Event" while not signed in):
screenshot from 2016-06-21 16 51 42

(Like I mentioned in the first edited comment at the top of this conversation, the green flash message is back..)

**Comment by lislis** [comment]
@ariaru is there still something (like fixing things) needed from our side?

**Comment by lisbethmarianne** [comment]
@lislis We fixed it by adding the js files. (Due to a rebase they were not loaded automatically.)

**Comment by lislis** [comment]
@lisbethmarianne ah, thanks. So all that's needed is a rebase?

**Comment by lisbethmarianne** [comment]
@lislis Don't think you have to do anything here right now. Have to consult with @ariaru what we still need.

**Comment by ariaru** [comment]
@lislis I think we are fine for now, thanks :) Will do the rebase. There is another missing view, but I will take care of that. I'll get back to you in case we need extra styling for that after it's done.

**Comment by ariaru** [comment]
To do:
- [ ] Events edit page: events controller, edit action, restricted to organizers and admins -- re-use events/_form
- [ ] Delete edit action + view from admin events controller/views
- [ ] List events on profile (= users show view)
- [ ] Only admins can change approved status
- [ ] Organizers can only edit and delete unapproved events
- [ ] Restrict who can see unapproved events and user profile
- [ ] Breadcrumbs should be adjusted according to role

**Comment by Powerglove** [comment]
Is this ready to merge, @ariaru ? Just making sure, it is such a historic moment!!

**Comment by ariaru** [comment]
@Powerglove Actually no, not yet -- see Slack for details

**Comment by fidothe** [comment]
ZOMG :shipit: 🚀 💯

**Pull request merged**
