### PR TITLE
show Apply link only when deadline is today or in the future

### PR DESCRIPTION
**Pull request by lisbethmarianne**
the Apply link was there until the end date of the event

changed to deadline

### CODE REVIEW

**Comment by ariaru** [comment]
Remember time zone issue!

**Comment by ariaru** [comment]
This has to be fixed before the deadline for CraftConf passes!

**Comment by lisbethmarianne** [comment]
Timezone issue was solved. Deadline will always be midnight Pacific Time (US & Canada). Do we have to state somewhere in the event / application what the exact deadline is?

**Comment by lisbethmarianne** [comment]
I think this is ready to merge, but we have to discuss the time zone (Issue #204)

**Comment by lisbethmarianne** [comment]
Deadline of RuhrJS is tomorrow. Just saying....

**Pull request merged**
