### PR TITLE
change basic authetication

### PR DESCRIPTION
**Pull request by lisbethmarianne**
fixes issue #79 

based on this on: 
http://berk.es/2011/03/29/simplest-authentication-in-rails-basic-authentication-with-a-logged_in-helper/

authenticate_or_request_with_http_basic puts the username and password on the request object, the authenticated? method checks if they are there

### CODE REVIEW

**Comment by fidothe** [comment]
So, this won't do what you want some of the time.

The reason we used the session to store the authenticated flag on was that we wanted to be able to show the admin link on non-admin pages so that admin users can get back to the admin pages from the nav bar. Basic auth is per-request, so you can't rely on it being set except on pages that are directly protected by basic auth

**Comment by lisbethmarianne** [comment]
Ok, thanks @fidothe , at least I tried. ;)

**Comment by fidothe** [comment]
@lisbethmarianne why don't you see if you can implement a `SessionsController` with  a `destroy` action and stick a link in the navbar (when you're logged in) that triggers it... :smiley:

**Comment by lisbethmarianne** [comment]
@fidothe I'm lost on this. The Sessions controller destroy action would kill the links (Admin, Logout) in the navbar (when I click on logout), but the user is still logged in. So when I type .../admin, I will still see the admin page. Also reset_session doesn't help with the initial problem #79.

All I can find is that with basic_authentication you have to close the browser to log out. Or do some crazy hacks.

**Pull request closed without merging**
