### PR TITLE
Footer Design update

### PR DESCRIPTION
**Pull request by bioshrimp**
And here is the updated footer with the icons.  Please check. :)

### CODE REVIEW

**Comment by lisbethmarianne** [comment]
why does it have the changes I made in app/views/events/_event.html.erb and app/views/events/preview.html.erb?

**Comment by lislis** [comment]
I believe it's a pull/ merge gone wrong. We'll check tonight and rebase or cherrypick :)

**Comment by bioshrimp** [comment]
I know it´s weird.  There was a conflict with my branch because it didn't have all the recent changes in it. So I copy&pasted them in manually even though they had nothing to do with the footer design but at least thhen the conflict was gone. But yeah, not sure I should have done it. Is this a problem now? sorry :D

**Comment by lisbethmarianne** [comment]
Sounds wild. :smile: Thanks for checking this...

**Comment by bioshrimp** [comment]
we cherry-picked on a different branch. closing this. check the real thing:  #171

**Pull request closed without merging**
