### PR TITLE
New approach to two column layout

### PR DESCRIPTION
**Pull request by lislis**
now in admin_events#index and events#edit
More to come!

### CODE REVIEW

**Comment by lislis** [comment]
@lisbethmarianne hey there 👋 This is sort of good to go. Do you want to check it?

**Comment by lisbethmarianne** [comment]
@lislis Can you check in Chrome and Safari? There is a space on the top of the second column, that isn't there in Firefox.

bildschirmfoto 2016-08-22 um 20 41 00

**Comment by lislis** [comment]
@lisbethmarianne seems like this height difference is an inconsistency in the way browsers implement the `columns` property. There is no way we can fix this other than waiting for browsers to update their implementation.
The thing is that I find this approach the most accessible to use because you just need a container element with the `two-columns` class.
I'm gonna rebase the branch and then you can decide whether you want it or not :D

**Comment by lisbethmarianne** [comment]
@lislis It is not my decision. It is as much your project as it is mine. And you understand much more about the css and design of this app. So go ahead and merge it. :+1: 🚀

**Comment by lislis** [comment]
It looks good so far. Gonna 🚢 it!

**Pull request merged**
